#! /bin/bash

#coding: utf-8
################################################################
# CLEAN ENERGY SOLUTIONS - 2018
#
# Close
#
# Create by: Emílio Palote Santos
#
# Repository: https://github.com/cleanenergy/DataCollector
#
# This code close all instances of DataCollector running now
#
################################################################

kill $(pgrep -f "python3 main.py")