#! /bin/bash

#coding: utf-8
################################################################
# CLEAN ENERGY SOLUTIONS - 2018
#
# Setup
#
# Create by: Emílio Palote Santos
#
# Repository: https://github.com/cleanenergy/DataCollector
#
# This code setup a autostart to DataCollector system after the login
#
################################################################

# Verify if exist old configurations 
if grep -q dev/DataCollector/DataCollector "$HOME/.config/lxsession/LXDE-pi/autostart"
then
	crontab -l > $HOME/dev/DataCollector/tempcron

	if grep -q dev/DataCollector/tempcron "$HOME/dev/DataCollector/cronrun"
	then
		rm $HOME/dev/DataCollector/tempcron
		exit 1
	fi
	echo "@midnight $HOME/dev/DataCollector/cronrun" >> $HOME/dev/DataCollector/tempcron
	crontab $HOME/dev/DataCollector/tempcron
	rm $HOME/dev/DataCollector/tempcron

fi
# If not

# Adjust Crontab
crontab -l > $HOME/dev/DataCollector/tempcron
echo "@midnight $HOME/dev/DataCollector/cronrun" >> $HOME/dev/DataCollector/tempcron
crontab $HOME/dev/DataCollector/tempcron
rm $HOME/dev/DataCollector/tempcron

# Adjust 
echo "@$HOME/dev/DataCollector/DataCollector" >> $HOME/.config/lxsession/LXDE-pi/autostart
