#! /bin/bash

#coding: utf-8
################################################################
# CLEAN ENERGY SOLUTIONS - 2018
#
# Setup
#
# Create by: Emílio Palote Santos
#
# Repository: https://github.com/cleanenergy/DataCollector
#
# This code setup a autostart to DataCollector system after the login
#
################################################################

# Verify if exist old configurations for Auto Start
if grep -q dev/DataCollector/DataCollector "$HOME/.config/lxsession/LXDE-pi/autostart"
then
	:
else
	echo "@$HOME/dev/DataCollector/DataCollector" >> $HOME/.config/lxsession/LXDE-pi/autostart
fi

# Verify if exist old configurations for Root Cron Config
sudo crontab -l > $HOME/dev/DataCollector/rootcron
if grep -q dev/DataCollector/cronrun "$HOME/dev/DataCollector/rootcron"
then
	:
else
	echo "@midnight sudo $HOME/dev/DataCollector/cronrun" >> $HOME/dev/DataCollector/rootcron
	sudo crontab $HOME/dev/DataCollector/rootcron
fi
# Verify if exist old configurations for User Cron Config
crontab -l > $HOME/dev/DataCollector/usercron
if grep -q dev/DataCollector/DataCollector "$HOME/dev/DataCollector/usercron"
then
	:
else
	echo "* * * * * export DISPLAY=:0; $HOME/dev/DataCollector/DataCollector" >> $HOME/dev/DataCollector/usercron
	crontab $HOME/dev/DataCollector/usercron
fi

rm $HOME/dev/DataCollector/usercron
rm $HOME/dev/DataCollector/rootcron

exit 1
